### ISSUE TITLE
Relax geojson crate version requirements

### ISSUE THREAD

**Issue by pjsier** [georust/topojson#10]
It looks like the tests pass with `geojson` 0.19.0, so it may be worth relaxing the requirements here. Should the new requirement be ">=0.16, <0.20" for now? Looks like the 0.20.0 release might be soon though and not sure if any of the changes there would be breaking

I haven't been active in the georust organization in a while, but interested in getting involved again! Wanted to check on this first though

**Comment by frewsxcv** [comment]
If you've verified that all of those geojson versions are compatible with the topojson crate, then relaxing the requirements seems like an improvement. Ideally we would have CI test each version of the geojson crate in a test matrix, but not a blocker to moving forward with this

**Comment by pjsier** [comment]
Sounds good to me, I'll put in a PR.

I'd be interested in building out the CI for this as well if that sounds worthwhile. I've worked more with GitHub Actions than Travis CI, and it looks like some of the more active georust crates are using GitHub Actions, but I'm open to either since it sounds like that's an active conversation

**Comment by frewsxcv** [comment]
We don't have an official stance or recommendation between the two, though I also personally prefer GitHub Actions so that'd be my vote
