### ISSUE TITLE
Add GitHub Actions CI

### ISSUE THREAD

**Issue by pjsier** [georust/topojson#12]
Moving from the conversation in #10, it sounds like it would be useful to run checks against multiple versions of the `geojson` crate as well as stable and nightly Rust. At minimum this should match the current Travis CI functionality running `cargo build` and `cargo test`, but we could also run `rustfmt` and `clippy`.

It looks like right now those additional checks would fail, and I'm not sure if that's a priority here, but wanted to see what others think before moving forward.

**Comment by michaelkirk** [comment]
GH actions have typically run just a little bit faster for us on the geo and proj crates, and their macos builds seem less prone to huge delays.

**Comment by pjsier** [comment]
Closing now that #13 and #15 are merged
