### ISSUE TITLE
Add PartialEq to Error

### ISSUE THREAD

**Issue by tredoe** [georust/topojson#3]
Add `#[derive(Debug, PartialEq)]` to the error so it could be compared in tests of other libraries/apps that use your library.

https://github.com/georust/rust-topojson/blob/master/src/error.rs#L5

**Comment by tredoe** [comment]
https://www.reddit.com/r/rust/comments/5d8frm/traits_derived_in_errors/

**Comment by frewsxcv** [comment]
@kless Do you want to try opening a PR for this? You should be able to edit the file in GitHub's web UI and just add the derived traits. Not worried about tests for this

**Comment by tredoe** [comment]
[PR](https://github.com/georust/rust-topojson/pull/4)
