### ISSUE TITLE
Added to crates.io?

### ISSUE THREAD

**Issue by tredoe** [georust/topojson#5]
Why does TopoJSON has not been added to (crates.io) ?

**Comment by frewsxcv** [comment]
As of right now, rust-topojson uses a git dependency for rust-geojson:

https://github.com/georust/rust-topojson/blob/master/Cargo.toml#L14

There are two problems here:

* One cannot publish to crates.io with git dependencies
* rust-topojson doesn't work with the latest version of rust-geojson

**Comment by frewsxcv** [comment]
as of https://github.com/georust/topojson/pull/6, the topojson crate is on crates.io
