### ISSUE TITLE
Adding the georust:core team as owner of this crate ?

### ISSUE THREAD

**Issue by mthh** [georust/topojson#9]
It appears (according to https://crates.io/teams/github:georust:core) that most of the georust's crates have the whole team as owner but it's not the case for the [topojson](https://crates.io/crates/topojson) crate.

Could this also be the case for this one ?
There is the 0.2.0 version that could be released !

/cc @frewsxcv

**Comment by frewsxcv** [comment]
Done!

**Comment by mthh** [comment]
Thanks !
